[character]
error_symbol = "[âœ˜](bold red)"

[aws]
format = ' on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "îŒ½ "
#symbol = "ğŸ…° "

[aws.region_aliases]
us-east-2 = "ue2"
us-east-1 = "ue1"

[git_branch]
# symbol = "ğŸŒ± "
symbol = "ï˜ "
truncation_length = 25

[git_commit]
commit_hash_length = 6
# tag_symbol = "ğŸ”– "
tag_disabled = false

[git_status]
conflicted = 'ğŸ³[\(${count}\)](bold red)'
untracked = 'ğŸ¤·[\(${count}\)](blue)'
modified = 'ğŸ“[\(${count}\)](yellow)'
staged = '[++\(${count}\)](green)'
deleted = 'ğŸ—‘[\(${count}\)](red)'
stashed = 'ğŸ“¦'
renamed = 'ğŸ‘…'
ahead = '[â‡¡\(${count}\)](green)'
diverged = '[â‡•â‡¡${ahead_count}â‡£${behind_count}](yellow)'
behind = '[â‡£\(${count}\)](red)'

[python]
format = "[$symbol$version]($style)"
symbol = "îˆµ "
style = "bold yellow"

[conda]
format = "[$symbol$environment ]($style)"
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "white"
disabled = false

